name: Release on PR Merge to Main

on:
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  release:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get latest tag
        id: get-latest-tag
        run: |
          LATEST_TAG=$(git describe --tags --abbrev=0)
          echo "LATEST_TAG=$LATEST_TAG" >> $GITHUB_ENV

      - name: Increment tag version (minor)
        id: increment-version
        run: |
          NEW_TAG=$(echo $LATEST_TAG | awk -F. '{$2=$2+1}1' OFS=. | awk '{$3=0}1' OFS=.)
          echo "NEW_TAG=$NEW_TAG" >> $GITHUB_ENV

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.LATEST_TAG }}
          release_name: Release ${{ env.LATEST_TAG }}
          draft: false
          prerelease: false

      - name: Inform about release URL
        run: echo "Release was published at ${{ steps.create_release.outputs.html_url }}"
